- name: Create folders /home/setup-asterisk/
  file:
    path: /home/setup-asterisk/
    mode: 0755
    state: directory
    owner: root
    group: root

- name: Extract file setup asterisk version 13.23.1
  unarchive:
    src: asterisk-13.23.1.tar.gz
    dest: /home/setup-asterisk/

- name: Execuite the script enable mp3 support
  command: ./contrib/scripts/get_mp3_source.sh
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk source code
  command: ./contrib/scripts/install_prereq install
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk source code
  command: ./configure --libdir=/usr/lib64 
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Create menuselect.makeopts
  command: make menuselect.makeopts
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk select addon menuselect
  command: menuselect/menuselect --enable chan_mobile --enable chan_ooh323 --enable format_mp3 --enable res_config_mysql --enable app_mysql --enable cdr_mysql
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk source code make
  command: make
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk source code make install 
  command: make install
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk source code make samples
  command: make samples
  args:
    chdir: '{{ asterisk_src_dir }}'

- name: Configure asterisk source code make config
  command: make config
  args:
    chdir: '{{ asterisk_src_dir }}'
